import streamlit as st
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from analyzer.checker import analyze_file

st.set_page_config(page_title="LeakGuard Dashboard", page_icon=":shield:", layout="wide")

st.title("LeakGuard - Resource Leak Detection Dashboard")
st.markdown("---")

# ── SIDEBAR ──────────────────────────────────────────────────────────────────
scan_target = st.sidebar.text_input("Target directory to scan", value="test_repo")
run_scan = st.sidebar.button("Run AST Analysis", type="primary", use_container_width=True)

# ── LOAD ML MODELS LAZY ──────────────────────────────────────────────────────
@st.cache_resource
def load_ml():
    try:
        from ml_pipeline.predictor import get_leak_confidence, categorize_risk
        return get_leak_confidence, categorize_risk
    except Exception:
        return None, None

get_leak_confidence, categorize_risk = load_ml()

# ── SCAN ─────────────────────────────────────────────────────────────────────
if run_scan:
    if not os.path.exists(scan_target):
        st.error(f"Directory `{scan_target}` not found.")
        st.stop()

    all_findings = []
    safe_files = []

    for root, _, files in os.walk(scan_target):
        for fname in files:
            if fname.endswith(".py"):
                fpath = os.path.join(root, fname)
                leaks = analyze_file(fpath)
                if leaks:
                    all_findings.extend(leaks)
                else:
                    safe_files.append(fpath)

    definite = [f for f in all_findings if f["status"] == "LEAK"]
    uncertain = [f for f in all_findings if f["status"] == "UNCERTAIN"]

    # ── SECTION 1: AST ENGINE REPORT ─────────────────────────────────────
    st.header("AST Engine Baseline Report")
    st.caption("Generated by LeakGuard AST engine - path-sensitive, control-flow-aware analysis")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.subheader("Safe")
        st.metric("Files", len(safe_files))
        if safe_files:
            for fp in safe_files:
                st.success(f"`{fp}`")

    with col2:
        st.subheader("Definite Leaks")
        st.metric("Files", len(definite))
        if definite:
            for item in definite:
                st.error(
                    f"`{item['file_name']}` :red[**Line {item['line_number']}**] "
                    f"- `{item['resource_name']}` - {item['leak_type']}"
                )
        else:
            st.success("No definite leaks detected.")

    with col3:
        st.subheader("Uncertain Ownership")
        st.metric("Files", len(uncertain))
        if uncertain:
            for item in uncertain:
                st.warning(
                    f"`{item['file_name']}` :orange[**Line {item['line_number']}**] "
                    f"- `{item['resource_name']}` - {item['leak_type']}"
                )
        else:
            st.success("No uncertain cases.")

    st.markdown("---")

    # ── SECTION 2: ML RISK DASHBOARD ─────────────────────────────────────
    st.header("ML Risk Categorization")
    st.caption("Uncertain AST items scored by Random Forest model - categorized into HIGH / MEDIUM / LOW risk")

    if not uncertain:
        st.info("No uncertain items to categorize.")
    elif get_leak_confidence is None:
        st.warning("ML model not available. Train it first: `python ml_pipeline/train_model.py`")
    else:
        high_risks = []
        medium_risks = []
        low_risks = []

        for item in uncertain:
            conf = get_leak_confidence(item["file_name"])
            if conf is not None:
                risk = categorize_risk(conf)
                entry = {**item, "confidence": conf, "risk": risk}
                if risk["tier"] == "HIGH":
                    high_risks.append(entry)
                elif risk["tier"] == "MEDIUM":
                    medium_risks.append(entry)
                else:
                    low_risks.append(entry)

        ml_col1, ml_col2, ml_col3 = st.columns(3)

        with ml_col1:
            st.subheader("High Risk")
            st.metric("Count", len(high_risks))
            if high_risks:
                for entry in high_risks:
                    st.error(
                        f"`{entry['file_name']}` :red[**Line {entry['line_number']}**] "
                        f"- `{entry['resource_name']}`\n"
                        f"Confidence: {entry['confidence']:.1f}% | Action: {entry['risk']['action']}"
                    )

        with ml_col2:
            st.subheader("Medium Risk")
            st.metric("Count", len(medium_risks))
            if medium_risks:
                for entry in medium_risks:
                    st.warning(
                        f"`{entry['file_name']}` :orange[**Line {entry['line_number']}**] "
                        f"- `{entry['resource_name']}`\n"
                        f"Confidence: {entry['confidence']:.1f}% | Action: {entry['risk']['action']}"
                    )

        with ml_col3:
            st.subheader("Low Risk")
            st.metric("Count", len(low_risks))
            if low_risks:
                for entry in low_risks:
                    st.success(
                        f"`{entry['file_name']}` :green[**Line {entry['line_number']}**] "
                        f"- `{entry['resource_name']}`\n"
                        f"Confidence: {entry['confidence']:.1f}% | Action: {entry['risk']['action']}"
                    )

    st.markdown("---")

    # ── SECTION 3: INTERACTIVE AI REMEDIATION ────────────────────────────
    st.header("AI-Powered Auto-Remediation")
    st.caption("Uses Google Gemini to refactor leaking code into safe patterns")

    fixable = [f for f in definite if f["status"] == "LEAK"]

    if not fixable:
        st.info("No definite leaks to remediate.")
    else:
        st.write(f"**{len(fixable)}** resource leak(s) detected. Do you want to use AI to resolve these?")

        for item in fixable:
            st.write(
                f"- `{item['file_name']}` **Line {item['line_number']}**: "
                f"`{item['resource_name']}` ({item['leak_type']})"
            )

        st.markdown("")
        resolve_btn = st.button("Resolve All Leaks with AI", type="primary", use_container_width=True)

        if resolve_btn:
            api_key = os.environ.get("GEMINI_API_KEY", "")
            if not api_key:
                st.error("GEMINI_API_KEY not set. Export it or add it to your environment.")
            else:
                from ml_pipeline.genai_patcher import generate_safe_code

                progress = st.progress(0)
                log_area = st.empty()

                for idx, item in enumerate(fixable):
                    fpath = item["file_name"]
                    line_num = item["line_number"]
                    var_name = item["resource_name"]
                    leak_type = item["leak_type"]

                    st.write(f"Processing `{fpath}` Line {line_num} - `{var_name}`...")

                    try:
                        with open(fpath, "r", encoding="utf-8") as f:
                            original_lines = f.readlines()
                    except FileNotFoundError:
                        st.warning(f"File `{fpath}` not found, skipping.")
                        continue

                    open_line = original_lines[line_num - 1]
                    indent = len(open_line) - len(open_line.lstrip())
                    indent_str = " " * indent

                    st.info(
                        f"**Before** (`{fpath}:{line_num}`):\n"
                        f"```python\n{open_line.rstrip()}\n```"
                    )

                    log_area.text(
                        f"[{idx+1}/{len(fixable)}] Consulting GenAI for {fpath} Line {line_num}..."
                    )

                    safe_code = generate_safe_code(fpath, line_num, var_name)

                    if safe_code:
                        try:
                            with open(fpath, "w", encoding="utf-8") as f:
                                f.write(safe_code)
                        except Exception as e:
                            st.error(f"Failed to write file: {e}")
                            continue

                        with open(fpath, "r", encoding="utf-8") as f:
                            new_lines = f.readlines()

                        new_line = ""
                        if line_num - 1 < len(new_lines):
                            new_line = new_lines[line_num - 1].rstrip()

                        st.success(
                            f"**After** (`{fpath}:{line_num}`):\n"
                            f"```python\n{new_line}\n```"
                        )
                        st.write(f"Full file overwritten with refactored code.")
                    else:
                        patch = f"{indent_str}{var_name}.close()  # [LeakGuard Auto-Patch]"
                        original_lines.insert(line_num, patch + "\n")
                        try:
                            with open(fpath, "w", encoding="utf-8") as f:
                                f.writelines(original_lines)
                        except Exception as e:
                            st.error(f"Failed to write file: {e}")
                            continue

                        new_line = original_lines[line_num].rstrip()
                        st.success(
                            f"**After** (`{fpath}:{line_num}`):\n"
                            f"```python\n{new_line}\n```"
                        )
                        st.write(f"Injected `{var_name}.close()` after line {line_num}.")

                    progress.progress((idx + 1) / len(fixable))

                log_area.text("All leaks processed.")
                st.success("AI remediation complete. All files updated on disk.")
else:
    st.info("Configure a target directory in the sidebar and click **Run AST Analysis** to begin.")
